version = "3.11.1"
runner.dialect = scala212

preset=default
maxColumn = 120
assumeStandardLibraryStripMargin = false
align = none
align.openParenDefnSite = false
align.openParenCallSite = false
align.tokens = []
danglingParentheses = false
align.stripMargin = true
indent.defnSite = 4
danglingParentheses.defnSite = false
danglingParentheses.callSite = false

docstrings.style = Asterisk
rewrite.rules = [RedundantBraces, RedundantParens, SortModifiers]
rewrite.redundantBraces.stringInterpolation = true
rewrite.redundantBraces.generalExpressions = false
rewrite.redundantBraces.ifElseExpressions = false
rewrite.redundantBraces.methodBodies = true
rewrite.redundantBraces.parensForOneLineApply = true
rewrite.redundantParens.infixSide = all
rewrite.trailingCommas.style = never

optIn.configStyleArguments = false
newlines.forceBeforeMultilineAssign = any
newlines.afterCurlyLambdaParams=squash
