rules = [
  RemoveUnused,
  OrganizeImports
]

OrganizeImports {
  groupedImports = Keep
  coalesceToWildcardImportThreshold = 3
  groups = [
    "re:javax?\\.",
    "scala.",
    "*"
  ]
}

triggered.rules = [
  RemoveUnused,
  OrganizeImports
]
