// Code generated by Nomos. DO NOT EDIT.
package com.example.models

import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.databind.SerializationFeature
import com.fasterxml.jackson.module.scala.DefaultScalaModule
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule
import dev.cjfravel.nomos.model._
import dev.cjfravel.nomos.validation.{MultiValidator, ValidationError}
import com.fasterxml.jackson.databind.JsonNode
import scala.collection.immutable.ListMap

/**
 * Provides Jackson ObjectMapper with Scala module support.
 * The Scala module enables automatic serialization/deserialization of case classes.
 * Also contains the embedded template for runtime validation.
 * Import NomosFormats._ to use the mapper in your code.
 */
object NomosFormats {
  // Create a shared ObjectMapper instance with Scala module
  val mapper: ObjectMapper = {
    val m = new ObjectMapper()
    m.registerModule(DefaultScalaModule)
    m.registerModule(new JavaTimeModule())
    m.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS)
    m
  }

  // Embedded template for runtime validation
  lazy val embeddedTemplate: MultiTemplate = {
    MultiTemplate(
          basePackage = "com.example.models",
          definitions = List(
          TemplateDefinition(
            name = "User",
            templateType = ObjectType(ListMap("id" -> FieldDef(StringType(List()), optional = false), "username" -> FieldDef(StringType(List()), optional = false), "email" -> FieldDef(StringType(List()), optional = false), "age" -> FieldDef(NumberType(List()), optional = true), "roles" -> FieldDef(ArrayType(StringType(List()), List()), optional = false)), ForbidExtra),
            subPackage = Some("user"),
            description = Some("User model with basic information"),
            validators = List(),
            methods = List()
          ),
          TemplateDefinition(
            name = "Column",
            templateType = TypeDiscriminator(
              fieldName = "type",
              variants = ListMap("Decimal" -> ObjectType(ListMap("scale" -> FieldDef(IntType(List()), optional = false))), "Varchar" -> ObjectType(ListMap())),
              commonFields = ListMap(),
              includeInOutput = true,
              variantNames = Map.empty[String, String],
              variantMatch = "prefix",
              variantSubPackage = None
            ),
            subPackage = Some("column"),
            description = Some("Data contract column with parameterized type tags"),
            validators = List(),
            methods = List()
          ),
          TemplateDefinition(
            name = "Limits",
            templateType = ObjectType(ListMap("name" -> FieldDef(StringType(List()), optional = false), "maxFiles" -> FieldDef(IntType(List()), optional = true, nullable = true)), ForbidExtra),
            subPackage = Some("limits"),
            description = None,
            validators = List(),
            methods = List()
          ),
          TemplateDefinition(
            name = "Account",
            templateType = ObjectType(ListMap("accountId" -> FieldDef(StringType(List()), optional = false), "active" -> FieldDef(BooleanType(), optional = false), "openedOn" -> FieldDef(DateType(), optional = false), "tier" -> FieldDef(EnumType("Tier", List("free", "pro")), optional = false)), ForbidExtra),
            subPackage = Some("account"),
            description = Some("Account model in a sibling package"),
            validators = List(),
            methods = List("def label: String = accountId + \"/\" + active")
          )
          ),
          useOptionTypes = true,
          listType = "List",
          fromJsonStyle = "either"
        )
  }

  // Validator instance using the embedded template
  lazy val validator: MultiValidator = new MultiValidator(embeddedTemplate)
}
