// Code generated by Nomos. DO NOT EDIT.
package com.example.models

import dev.cjfravel.nomos.model._
import dev.cjfravel.nomos.validation.MultiValidator
import scala.collection.immutable.ListMap

/**
 * Holds the embedded template and a validator for runtime validation.
 * Generated companions import this to validate without the original template file.
 */
object NomosFormats {
  // Embedded template for runtime validation
  lazy val embeddedTemplate: MultiTemplate = {
    MultiTemplate(
          basePackage = "com.example.models",
          definitions = List(
          TemplateDefinition(
            name = "User",
            templateType = ObjectType(ListMap("id" -> FieldDef(StringType(List()), optional = false), "username" -> FieldDef(StringType(List()), optional = false), "email" -> FieldDef(StringType(List()), optional = false), "age" -> FieldDef(NumberType(List()), optional = true), "roles" -> FieldDef(ArrayType(StringType(List()), List()), optional = false)), ForbidExtra),
            subPackage = Some("user"),
            description = Some("User model with basic information"),
            validators = List(),
            methods = List()
          ),
          TemplateDefinition(
            name = "Column",
            templateType = TypeDiscriminator(
              fieldName = "type",
              variants = ListMap("Decimal" -> ObjectType(ListMap("scale" -> FieldDef(IntType(List()), optional = false))), "Varchar" -> ObjectType(ListMap())),
              commonFields = ListMap(),
              includeInOutput = true,
              variantNames = Map.empty[String, String],
              variantMatch = "prefix",
              variantSubPackage = None
            ),
            subPackage = Some("column"),
            description = Some("Data contract column with parameterized type tags"),
            validators = List(),
            methods = List()
          ),
          TemplateDefinition(
            name = "Limits",
            templateType = ObjectType(ListMap("name" -> FieldDef(StringType(List()), optional = false), "maxFiles" -> FieldDef(IntType(List()), optional = true, nullable = true), "attributes" -> FieldDef(ObjectType(ListMap(), TypedExtra(StringType(List()))), optional = false)), ForbidExtra),
            subPackage = Some("limits"),
            description = None,
            validators = List(),
            methods = List()
          ),
          TemplateDefinition(
            name = "Account",
            templateType = ObjectType(ListMap("accountId" -> FieldDef(StringType(List()), optional = false), "active" -> FieldDef(BooleanType(), optional = false), "openedOn" -> FieldDef(DateType(), optional = false), "tier" -> FieldDef(EnumType("Tier", List("free", "pro")), optional = false)), ForbidExtra),
            subPackage = Some("account"),
            description = Some("Account model in a sibling package"),
            validators = List(),
            methods = List("def label: String = accountId + \"/\" + active")
          )
          ),
          useOptionTypes = true,
          listType = "List",
          fromJsonStyle = "either"
        )
  }

  // Validator instance using the embedded template
  lazy val validator: MultiValidator = new MultiValidator(embeddedTemplate)
}
