// Code generated by Nomos. DO NOT EDIT.
// Source: com/example/models/account/account.json
package com.example.models.account

case class Account(
  accountId: String,
  active: Boolean,
  openedOn: java.time.LocalDate,
  tier: Tier
) {
  def label: String = accountId + "/" + active
}

object Account {
  import com.example.models.NomosFormats
  import NomosFormats._
  import dev.cjfravel.nomos.json._
  import dev.cjfravel.nomos.serialization.{Codecs, CodecRegistry}
  import dev.cjfravel.nomos.validation.ValidationError

  def decode(json: JsonValue): Either[String, Account] = json match {
    case o: JsonObject =>
      for {
        accountId <- Codecs.required(o, "accountId", Codecs.string)
        active <- Codecs.required(o, "active", Codecs.boolean)
        openedOn <- Codecs.required(o, "openedOn", Codecs.temporal[java.time.LocalDate]("date", s => java.time.LocalDate.parse(s)))
        tier <- Codecs.required(o, "tier", Tier.decode)
      } yield Account(accountId, active, openedOn, tier)
    case other => Left("Account: expected object, got " + other.typeName)
  }

  def encode(obj: Account): JsonValue = JsonObject.fromFields(List(
    Some("accountId" -> JsonString(obj.accountId)),
    Some("active" -> JsonBoolean(obj.active)),
    Some("openedOn" -> JsonString(obj.openedOn.toString)),
    Some("tier" -> Tier.encode(obj.tier))
  ).flatten)

  def fromJson(json: String): Either[String, Account] = Json.parse(json).right.flatMap(decode)

  def toJson(obj: Account): String = Json.write(encode(obj))

  /**
   * Validates JSON against the embedded template and returns a parsed instance.
   * This allows validation without needing the original template file.
   */
  def validate(json: String): Either[List[ValidationError], Account] = {
    validator.validate(json, "com.example.models.account.Account") match {
      case Right(_) => fromJson(json).left.map(err => List(ValidationError("root", err, "valid JSON", json)))
      case Left(errors) => Left(errors)
    }
  }
}
