// Code generated by Nomos. DO NOT EDIT.
// Source: com/example/models/account/account.json
package com.example.models.account

import dev.cjfravel.nomos.json.{JsonValue, JsonString}

sealed trait Tier

object Tier {
  case object Free extends Tier
  case object Pro extends Tier

  val values: List[Tier] = List(Free, Pro)

  def fromString(s: String): Option[Tier] = s match {
    case "free" => Some(Free)
    case "pro" => Some(Pro)
    case _ => None
  }

  def asString(v: Tier): String = v match {
    case Free => "free"
    case Pro => "pro"
  }

  def decode(json: JsonValue): Either[String, Tier] = json match {
    case JsonString(s) => fromString(s).toRight("invalid Tier: " + s)
    case other => Left("expected string, got " + other.typeName)
  }

  def encode(v: Tier): JsonValue = JsonString(asString(v))
}
