// Code generated by Nomos. DO NOT EDIT.
// Source: com/example/models/user.json
package com.example.models.user

case class User(
  id: String,
  username: String,
  email: String,
  age: Option[Double],
  roles: List[String]
)

object User {
  import com.example.models.NomosFormats
  import NomosFormats._
  import dev.cjfravel.nomos.json._
  import dev.cjfravel.nomos.serialization.{Codecs, CodecRegistry}
  import dev.cjfravel.nomos.validation.ValidationError

  def decode(json: JsonValue): Either[String, User] = json match {
    case o: JsonObject =>
      for {
        id <- Codecs.required(o, "id", Codecs.string)
        username <- Codecs.required(o, "username", Codecs.string)
        email <- Codecs.required(o, "email", Codecs.string)
        age <- Codecs.optional(o, "age", Codecs.double)
        roles <- Codecs.required(o, "roles", Codecs.list(Codecs.string))
      } yield User(id, username, email, age, roles)
    case other => Left("User: expected object, got " + other.typeName)
  }

  def encode(obj: User): JsonValue = JsonObject.fromFields(List(
    Some("id" -> JsonString(obj.id)),
    Some("username" -> JsonString(obj.username)),
    Some("email" -> JsonString(obj.email)),
    obj.age.map(v => "age" -> JsonNumber.fromDouble(v)),
    Some("roles" -> JsonArray(obj.roles.iterator.map(x => JsonString(x)).toVector))
  ).flatten)

  def fromJson(json: String): Either[String, User] = Json.parse(json).right.flatMap(decode)

  def toJson(obj: User): String = Json.write(encode(obj))

  /**
   * Validates JSON against the embedded template and returns a parsed instance.
   * This allows validation without needing the original template file.
   */
  def validate(json: String): Either[List[ValidationError], User] = {
    validator.validate(json, "com.example.models.user.User") match {
      case Right(_) => fromJson(json).left.map(err => List(ValidationError("root", err, "valid JSON", json)))
      case Left(errors) => Left(errors)
    }
  }
}
