// Code generated by Nomos. DO NOT EDIT.
// Source: com/example/models/limits/limits.json
package com.example.models.limits

case class Limits(
  name: String,
  maxFiles: java.lang.Integer = null
)

object Limits {
  import com.example.models.NomosFormats
  import NomosFormats._
  import dev.cjfravel.nomos.validation.ValidationError

  def fromJson(json: String): Either[String, Limits] = {
    try {
      Right(mapper.readValue(json, classOf[Limits]))
    } catch {
      case e: Exception => Left(s"Failed to parse JSON: ${e.getMessage}")
    }
  }

  def toJson(obj: Limits): String = {
    mapper.writeValueAsString(obj)
  }

  /**
   * Validates JSON against the embedded template and returns a parsed instance.
   * This allows validation without needing the original template file.
   */
  def validate(json: String): Either[List[ValidationError], Limits] = {
    validator.validate(json, "com.example.models.limits.Limits") match {
      case Right(_) => fromJson(json).left.map(err => List(ValidationError("root", err, "valid JSON", json)))
      case Left(errors) => Left(errors)
    }
  }
}
