package dev.cjfravel.nomos

import scala.collection.immutable.ListMap

import dev.cjfravel.nomos.generation.{CodeGenerator, GeneratorConfig}
import dev.cjfravel.nomos.model._
import org.scalatest.EitherValues
import org.scalatest.flatspec.AnyFlatSpec
import org.scalatest.matchers.should.Matchers

class GeneratedHeaderSpec extends AnyFlatSpec with Matchers with EitherValues {

  val gen = new CodeGenerator(GeneratorConfig("com.example", "target/test-gen"))

  def withSource(sp: Option[String]): MultiTemplate =
    MultiTemplate(
      "com.example",
      List(
        TemplateDefinition(
          "User",
          ObjectType(ListMap("status" -> FieldDef(EnumType("Status", List("a", "b")), false))),
          sourcePath = sp)))

  "every generated file" should "start with the generated-by header" in {
    val files = gen.generateMulti(withSource(None)).value
    files.foreach(f => f.content.linesIterator.next() shouldBe "// Code generated by Nomos. DO NOT EDIT.")
  }

  "a definition with a source file" should "include a Source pointer" in {
    val user =
      gen.generateMulti(withSource(Some("com/example/models/user.json"))).value.find(_.fileName == "User.scala").get
    user.content should include("// Source: com/example/models/user.json")
  }

  "an enum file" should "inherit its definition's source pointer" in {
    val status =
      gen.generateMulti(withSource(Some("com/example/models/user.json"))).value.find(_.fileName == "Status.scala").get
    status.content should include("// Source: com/example/models/user.json")
    status.content.linesIterator.next() shouldBe "// Code generated by Nomos. DO NOT EDIT."
  }

  "a definition without a source file" should "use the generic header only (no Source line)" in {
    val user = gen.generateMulti(withSource(None)).value.find(_.fileName == "User.scala").get
    user.content should include("// Code generated by Nomos. DO NOT EDIT.")
    user.content should not include "// Source:"
  }

  "NomosFormats" should "use the generic header" in {
    val nf = gen.generateMulti(withSource(Some("x.json"))).value.find(_.fileName == "NomosFormats.scala").get
    nf.content.linesIterator.next() shouldBe "// Code generated by Nomos. DO NOT EDIT."
  }
}
