package dev.cjfravel.nomos

import dev.cjfravel.nomos.model._
import dev.cjfravel.nomos.generation.FileWriter
import org.scalatest.flatspec.AnyFlatSpec
import org.scalatest.matchers.should.Matchers
import org.scalatest.EitherValues
import java.io.File
import java.nio.file.Files
import java.nio.charset.StandardCharsets.UTF_8
import scala.collection.immutable.ListMap

/**
 * When a definition/template is removed, its previously-generated file must not linger as a stale
 * type. Generation prunes orphaned generated files (scoped to files carrying the generated header,
 * so hand-written sources are never deleted).
 */
class OrphanPruneSpec extends AnyFlatSpec with Matchers with EitherValues {

  private val header = "// Code generated by Nomos. DO NOT EDIT.\n"

  "FileWriter.pruneOrphans" should "delete a generated orphan but keep current and hand-written files" in {
    val dir = Files.createTempDirectory("nomos-prune").toFile
    def write(rel: String, content: String): File = {
      val f = new File(dir, rel); f.getParentFile.mkdirs(); Files.write(f.toPath, content.getBytes(UTF_8)); f
    }
    val kept = write("p/Kept.scala", header + "object Kept")
    val orphan = write("p/Orphan.scala", header + "object Orphan")
    val hand = write("p/Hand.scala", "object Hand") // no header

    val deleted = new FileWriter().pruneOrphans(dir, Set(kept))
    deleted.map(_.getName) should contain only "Orphan.scala"
    kept.exists shouldBe true
    hand.exists shouldBe true
    orphan.exists shouldBe false
  }

  "generateCode" should "remove a generated file whose definition was removed" in {
    val dir = Files.createTempDirectory("nomos-gen-prune").toFile
    def defn(n: String) = TemplateDefinition(n, ObjectType(ListMap("x" -> FieldDef(StringType(), optional = false))))

    Nomos.generateCode(MultiTemplate("com.example", List(defn("A"), defn("B"))), dir.getPath) shouldBe a[Right[_, _]]
    new File(dir, "com/example/A.scala").exists shouldBe true
    new File(dir, "com/example/B.scala").exists shouldBe true

    // Regenerate with only A: B.scala is now an orphan and is pruned.
    Nomos.generateCode(MultiTemplate("com.example", List(defn("A"))), dir.getPath) shouldBe a[Right[_, _]]
    new File(dir, "com/example/A.scala").exists shouldBe true
    new File(dir, "com/example/B.scala").exists shouldBe false
  }
}
