// Code generated by Nomos. DO NOT EDIT.
// Source: com/example/models/column/column.json
package com.example.models.column

sealed trait Column {
  val `type`: String
}

case class Decimal(
  `type`: String,
  scale: Int
) extends Column

case class Varchar(`type`: String) extends Column

object Column {
  import com.example.models.NomosFormats
  import NomosFormats._
  import dev.cjfravel.nomos.json._
  import dev.cjfravel.nomos.serialization.{Codecs, CodecRegistry}
  import dev.cjfravel.nomos.validation.ValidationError

  def decode(json: JsonValue): Either[String, Column] = json match {
    case o: JsonObject =>
      o.field("type") match {
        case Some(JsonString(d)) =>
          d match {
            case d2 if d2.startsWith("Decimal") =>
              for {
                scale <- Codecs.required(o, "scale", Codecs.int)
              } yield Decimal(d, scale)
            case d2 if d2.startsWith("Varchar") =>
              Right(Varchar(d))
            case other => Left("Unknown type value: " + other)
          }
        case Some(_) => Left("type: expected string")
        case None => Left("missing required field 'type'")
      }
    case other => Left("Column: expected object, got " + other.typeName)
  }

  def encode(obj: Column): JsonValue = obj match {
    case v: Decimal => JsonObject.fromFields(List(Some("type" -> JsonString(v.`type`)), Some("scale" -> JsonNumber.fromInt(v.scale))).flatten)
    case v: Varchar => JsonObject.fromFields(List(Some("type" -> JsonString(v.`type`))).flatten)
  }

  def fromJson(json: String): Either[String, Column] = Json.parse(json).right.flatMap(decode)

  def toJson(obj: Column): String = Json.write(encode(obj))

  /**
   * Validates JSON against the embedded template and returns a parsed instance.
   * This allows validation without needing the original template file.
   */
  def validate(json: String): Either[List[ValidationError], Column] = {
    validator.validate(json, "com.example.models.column.Column") match {
      case Right(_) => fromJson(json).left.map(err => List(ValidationError("root", err, "valid JSON", json)))
      case Left(errors) => Left(errors)
    }
  }
}

